version: '3.4'

services:
  react-nginx-app:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf
  backend:
    build: .
    expose:
      - 5000
    ports:
      - 5000:5000